### ISSUE TITLE
[V2] Improve session management

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/website#69]
The current session handling is very error prone and not reliable.

An expired session can result in silently failing requests when accessing or creating resources without any prompts to the user.
Expired sessions should either try to renew themselves or result in an logged-out state. 

### TODO:
 
- [ ] Improve session renew 
- [ ] Add force logout if renew fails
- [ ] Add toasts that indicate failure (including session failures)
- [ ] Remove any user-state on logout
