### ISSUE TITLE
Add alternative downloadlinks for objects

### ISSUE THREAD

**Issue by Stefan-JLU** [ArunaStorage/website#82]
---
name: alternative downloadlinks for objects
about: allow the user to see all endpoints of an object
title: 'alternative downloadlinks for objects'
labels: enhancement
assignees: 'Stefan Nitz'
---

### Overview
Show all Endpoints for an Object in an extra menu (accordeon)

An object might be stored in more than one location. Currently the download link takes the first endpoint (from the first location) and allows the user to download from there. If the first location is unavailable the user is not able to download the object eventhough accessible replicates are available. We want to give the user the possibility to access these other locations of their object.

### Tasks
- [x] add card with table of endpoints to pages/objects conditional on isDownloadable (see Download Button)
- [x] add endpoint name to table (fetch endpoint name first)
- [x] add human readable status (currently it's just the enum name)
- [x] add download button that only activates if the status is REPLICATION_STATUS_FINISHED

### Discussions
Further Ideas:
- Test in the frontend whether each endpoints is reachable
- check the state of the data proxys in the backend and show endpoints that might not work in the frontend
- a magic link to the API that will iterate through endpoints and return data from the first working one

Ideas for next ticket:
add expirydate for links (download link after ~5 Minutes, sharing link adjustable by user)
